"""empty message

Revision ID: 51048ec966d8
Revises: 0ef41eaa17e1
Create Date: 2017-04-02 23:21:30.400079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51048ec966d8'
down_revision = '0ef41eaa17e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('picture', sa.String(length=250), nullable=True))
    op.drop_column('user', 'picture_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('picture_url', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('user', 'picture')
    # ### end Alembic commands ###
