"""empty message

Revision ID: 82edb98cc4d1
Revises: adfca47a776a
Create Date: 2017-01-30 20:46:56.038691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82edb98cc4d1'
down_revision = 'adfca47a776a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
